<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="log4net" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" />
  </ItemGroup>

</Project>
